Parameters:
    EnvironmentName:
        Description: Single Parameter that we are passing with the env name.
        Type: String

Resources:
    BastionPubNet1:
        Type: AWS::EC2::Instance
        Properties:
            AvailabilityZone: !Select [ 0, !GetAZs '' ]
            ImageId: ami-0d1cd67c26f5fca19
            InstanceType: t2.micro
            SubnetId: 
                Fn::ImportValue; !Sub "${EnvironmentName}-PUB1-SN"